// Comprehensive raw input provided by the user
module.exports = {
  arabicRaw: [
    "آنا كومنينا: الألكسياد، ترجمة د. حسن حبشي، جـ1، طـ1، المجلس الأعلى للثقافة، القاهرة، 2004م.",
    "أبرار كريم الله: مذبحة التتار، ترجمة رشيدة رحيم الصبروتي، الهيئة المصرية العامة للكتاب، الإسكندرية، 1993م.",
    "أحمد زكى بك: قاموس الجغرافية القديمة، المطبعة الأميرية، القاهرة، 1899م.",
    "أحمد عبد الرحيم مصطفي: أصول التاريخ العثمانى، دار الشروق، القاهرة، 1982م.",
    "أحمد عبد السيد أحمد على الناصري: الروم والشرق الاسلامي، القاهرة، 1993م.",
    "أحمد عبد المقصود: الجماعات القطلونية.",
    "أحمد فؤاد متولي وهويدا محمد فهمي: تاريخ الدولة العثمانية منذ نشأتها حتى نهاية العصر الذهبي، انتراك للنشر، القاهرة، 2002م.",
    "أسد رستم: الروم فى سياستهم وحضارتهم ودينهم وصلاتهم بالعرب، دار المكشوف، بيروت، 1955م.",
    "أسماء محمد العراقي: العلاقات السياسية بين بيزنطة والغرب الأوربي من 1363 - 1453م، رسالة ماجستير، جامعة كفر الشيخ، 2011م.",
    "أميرة محمد محمود نافع: العثمانيون وأوروبا (735 - 805هـ / 1352 - 1402م)، دار عين للدراسات والبحوث، القاهرة، 2014م.",
    "أوزنلو يوسف بك آصاف: تاريخ سلاطين بنى عثمان، تقديم محمد زينهم محمد عزب، مطبعة مدبولى، القاهرة، 1995م.",
    "أومان: الامبراطورية البيزنطية، ترجمة د. مصطفى طه بدر، القاهرة، 1993م.",
    "إبراهيم مصباح عبد القوي: السياسة الخارجية للدولة البيزنطية فى عهد الامبراطور أندرونيكوس الثالث باليولوجوس، رسالة ماجستير، جامعة طنطا، 2006م.",
    "إدوارد جيبون: اضمحلال الامبراطورية الرومانية وسقوطها.",
    "إدوارد ميتشر كريس / إدوارد شيفرد كريسي: تاريخ الأتراك العثمانيين، ترجمة أحمد سالم سالم، دار جامعة حمد بن خليفة للنشر، الدوحة، 2019م.",
    "إسماعيل سرهنك: حقائق الأخبار عن دول البحار، جـ1، القاهرة، 1312هـ.",
    "ابتسام محمد العرابى: العلاقات السياسية بين بيزنطة والغرب الأوروبى.",
    "ابراهيم بك حليم: تاريخ الدولة العثمانية (المعروف بالتحفة الحليمية)، مؤسسة الكتب الثقافية، بيروت، 1988م.",
    "ابن البيبي: تاريخ سلاجقة الروم.",
    "ابن بطوطة: تحفة النظار في غرائب الأمصار وعجائب الأسفار.",
    "ابن حجر العسقلانى: أنباء الغمر بأبناء العمر، تحقيق حسن حبشى، دار الكتب المصرية، القاهرة، 1970م.",
    "ابن خلدون: ديوان المبتدأ والخبر.",
    "ابن عربشاه: عجائب المقدور في نوائب تيمور، تحقيق أحمد فايز الحمصى، مؤسسة الرسالة، بيروت، 1986م.",
    "اسحق عبيد: أوروبا في العصور الوسطى المفهوم والحضارة، دار الفكر العربى، القاهرة، 2006م.",
    "اسحق عبيد: الدولة البيزنطية في عصر الباليولوجوس (1261 - 1453م)، مطبعة دار الكتب، بيروت.",
    "الأمين أبو بكر: بيزنطة في الملاحم العربية، قراءة في سيرة الأميرة ذات الهمة، مجلة الآداب جامعة حلوان (العدد الأول)، 2001م.",
    "الخطيب الجوهرى: نزهة النفوس والأبدان في تواريخ الزمان، تحقيق حسن حبشى، مطبعة دار الكتب، القاهرة، 1971م.",
    "السيد الباز العرينى: الدولة البيزنطية، بيروت، 1982م.",
    "السيد محمد متولي: الدولة البيزنطية في عالم القرن الخامس عشر، رسالة ماجستير، جامعة المنصورة، 1998م.",
    "القرمانى: أخبار الدول وآثار الأول فى التاريخ، تحقيق فهمى سعد وأحمد حطيط، الطبعة الأولى، عالم الكتب، بيروت، 1992م.",
    "القلقشندي: صبح الأعشى فى صناعة الإنشا، جـ5، دار الكتب الأميرية، القاهرة، 1915م.",
    "المقريزي: السلوك لمعرفة دول الملوك، تحقيق محمد عبد القادر عطا، ط1، دار الكتب العلمية، بيروت، 1997م.",
    "برنارد لويس: إسطنبول وحضارة الخلافة الإسلامية، تعريب سيد رضوان علي، الدار السعودية للنشر والتوزيع، الرياض، 1982م.",
    "جوزيف داهفويس: سبع معارك فاصلة في العصور الوسطى، ترجمة محمد فتحى الشاعر، الهيئة المصرية للكتاب، القاهرة، 1986م.",
    "جوزيف نسيم يوسف: العدوان الصليبي على مصر، دار الكتب الجامعية، الإسكندرية، 1999م.",
    "جون باتريك كينروس: القرون العثمانية قيام وسقوط الإمبراطورية التركية.",
    "حاتم عبد الرحمن الطحاوي: اقتحام العثمانيين للقسطنطينية: شهادة المؤرخ البيزنطي دوكاس، مجلة الاجتهاد، بيروت، 1999م.",
    "حاتم عبد الرحمن الطحاوي: بيزنطة والمدن الإيطالية العلاقات التجارية 1081 – 1204م، القاهرة، 1998م.",
    "حاتم عبد الرحمن الطحاوي: معركة أنقرة 804هـ 1402م مقدماتها ونتائجها، 2001م.",
    "حسين ربيع: دراسات في تاريخ الدولة البيزنطية، القاهرة، 1986م.",
    "حسين مجيب المصرى: معجم الدولة العثمانية.",
    "خليل أفندى مطران: مرآة الأيام فى ملخص التاريخ العام، مصر، 1897م.",
    "روبير مانتران: تاريخ الدولة العثمانية، ترجمة بشير السباعى، دار الفكر للنشر والتوزيع، القاهرة، 1993م.",
    "زبيدة عطا: بلاد الترك فى العصور الوسطى.",
    "سارة العزب حسين عيسى: الحملة الصليبية على فارنا (وارنه) (1443 - 1444م)، رسالة ماجستير، جامعة القاهرة، 2017م.",
    "سالم الرشيدى: محمد الفاتح، ط2، دار البشير للثقافة، القاهرة، 2013م.",
    "ستيفن رنسيمان: الحضارة البيزنطية، ترجمة: عبد العزيز توفيق جاويد، الهيئة المصرية العامة للكتاب، القاهرة، 1997م.",
    "ستيفن رنسيمان: تاريخ الحروب الصليبية، ترجمة السيد الباز العرينى، دار الثقافة، بيروت، 1982م.",
    "سهيل صابان: المعجم الموسوعى للمصطلحات العثمانية التاريخية، مكتبة الملك فهد الوطنية، الرياض، 2000م.",
    "سيد أحمد محمود: تاريخ الدولة العثمانية.",
    "شارل ديل: البندقية جمهورية أرستقراطية، ترجمة أحمد عزت عبد الكريم وتوفيق إسكندر، دار المعارف، القاهرة، 1948م.",
    "شمس الدين سامي: قاموس الأعلام، استانبول، 1899م.",
    "صلاح ضبيع (أو حزين): العلاقات السياسية بين العثمانيين والامبراطورية البيزنطية في عهد آل باليولوجوس.",
    "طارق منصور: القسطنطينية في الكتابات الصليبية 1096 - 1204م دراسة تحليلية، مجلة المؤرخ المصري، العدد 29، 2006م.",
    "طارق منصور: المآدب الإمبراطورية ومراسمها في عهد الإمبراطور ليو السادس الحكيم، كتاب بيزنطة مدينة الحضارة والنظم، دار الفكر العربي، القاهرة، 2015م.",
    "طافور: رحلة طافور في عالم القرن الخامس عشر الميلادي، ترجمة وتقديم حسن حبشي، دار المعارف، القاهرة، 1968م.",
    "عادل زيتون: العلاقات الاقتصادية بين الشرق والغرب في العصور الوسطى، الطبعة الأولى، دار دمشق، 1980م.",
    "عبد الباسط على الفاخوري: تحفة الأبناء مختصر تاريخ الإسلام، ط1، مكتبة المعارف، بيروت، 1902م.",
    "عبد القادر أحمد اليوسف: الامبراطورية البيزنطية، بيروت، 1966م.",
    "عبد اللطيف أحمد على: التاريخ الرومانى، تحقيق حسان حلاق، دار النهضة العربية، بيروت، 2011م.",
    "عزيز سوريال عطية: العلاقات بين الشرق والغرب تاريخ - ثقافة - سياسة، ترجمة فليب صابر سيف، دار العلم العربى، القاهرة، 1972م.",
    "عصمت غنيم: الامبراطورية البيزنطية، الاسكندرية، 1995م.",
    "على عبد خليل أحمد: الدولة العثمانية في سنوات المحنة، دار الحامد للنشر، عمان، 2011م.",
    "على محمد الصلابى: السلطان محمد الفاتح وعوامل النهوض في عصره، دار الايمان للطبع والنشر، الإسكندرية، 2002م.",
    "كيت فليت: التجارة بين أوروبا والبلدان الإسلامية في ظل الدولة العثمانية، تعريب أيمن الأرمنازى، مكتبة العبيكان، الرياض، 2004م.",
    "ليلى عبد الجواد إسماعيل: القسطنطينية في ضوء كتابات الجغرافيين والرحالة المسلمين، مجلة المؤرخ المصري، 1989م.",
    "محمد أحمد النفيعى: زواج السلاطين العثمانية من الأجنبيات وأثره فى إضعاف الدولة العثمانية، رسالة ماجستير، جامعة أم القرى، مكة المكرمة.",
    "محمد أنيس: الدولة العثمانية والشرق العربى 1514 - 1914م، مكتبة الانجلو المصرية، القاهرة، 1981م.",
    "محمد جميل بيهم: فلسفة التاريخ العثمانى، دار صادر، بيروت، 1985م.",
    "محمد سهيل طقوش: تاريخ العثمانيين من قيام الدولة إلى الانقلاب على الخلافة، دار النفائس، بيروت، 2013م.",
    "محمد عثمان عبد الجليل: إبيروس وسياستها الخارجية، رسالة دكتوراة غير منشورة، كلية الآداب جامعة طنطا، 1997م.",
    "محمد فريد بك: تاريخ الدولة العلية العثمانية، تحقيق إحسان حقي، ط1، دار النفائس، القاهرة، 1986م.",
    "محمد مؤنس عوض: تاريخ الإمبراطورية البيزنطية.",
    "محمود سعيد عمران: معالم تاريخ الامبراطورية البيزنطية، دار المعرفة الجامعية، الإسكندرية، 2000م.",
    "محمود شاكر: التاريخ الإسلامي العهد العثماني، ط4، المكتب الإسلامي، بيروت، 2000م.",
    "محمود محمد الحويرى: تاريخ الدولة العثمانية في العصور الوسطى.",
    "مها حافظ عبد المهدى: الإمبراطور مانويل الثانى باليولوجوس وسياسته الخارجية (1391 - 1425 م)، رسالة ماجستير، جامعة سوهاج، 2008م.",
    "موريس كين: حضارة أوروبا في العصور الوسطى، ترجمة قاسم عبده قاسم، دار عين للدراسات، القاهرة، 2010م.",
    "موستراس: المعجم الجغرافي.",
    "ناهد عمر صالح: الاتحاد الكنسى فى عهد الإمبراطور يوحنا الخامس باليولوجوس (1354-1376م)، مجلة المؤرخ المصرى.",
    "نيقولا فاتان: صعود العثمانيين (1362 - 1451م).",
    "نيقولو باربارو: الفتح الإسلامى للقسطنطينية.",
    "هاملتون جب وهارولد باون: المجتمع الإسلامى والغرب، ترجمة أحمد إيبش، دار الكتب الوطنية، أبو ظبى، 2012م.",
    "وسام عبد العزيز فرج: بيزنطة قراءة في التاريخ السياسي والإداري، الطبعة الأولى، عين للدراسات والبحوث الإنسانية والاجتماعية، القاهرة، 2004م.",
    "ياسر مصطفي عبد الوهاب: حملة المارشال بوسيكو على الاسكندرية وسواحل بلاد الشام 1403م، مؤتمر اتحاد المؤرخين العرب حصاد 21، القاهرة، 2013م.",
    "ياسر مصطفي عبد الوهاب: علاقات التحالف العثمانى المملوكى ضد المغول وأثره على بيزنطه (1388-1402م).",
    "ياقوت الحموى: معجم البلدان، دار صادر، بيروت، 1977م.",
    "يلماز أوزتونا: تاريخ الدولة العثمانية.",
    "يلماز أوزتونا: موسوعة تاريخ الإمبراطورية السياسي والعسكرى والحضارى، ترجمة عدنان محمود سلمان، الدار العربية للموسوعات، بيروت، 2010م."
  ],
  foreignRaw: [
    "Akropolites, G., The History, trans. Ruth Macrides, Oxford University Press, 2007.",
    "Alix, M., Precis Del' Histoire Del' Empire ottoman, 1822.",
    "Angelov, D., The Byzantine Hellene, Cambridge University Press, 2019.",
    "Angold, M., The Byzantine Empire, 1025-1204: A Political History, 2nd ed., Longman, 1997.",
    "Anonim, Gazavat sultan murad b. mohammed Han 1443-1444.",
    "Asikpasaoglu, Asikpasaoglu Tarihi, Ankara, 1985.",
    "Atiya, A., the Crusade In later Middle Age, London, 1938.",
    "Babinger, F., Mehmed the Conqueror and His Time, 1978.",
    "Barker, J. W., Manuel II Palaeologus 1391-1425, New Jersey, 1969.",
    "Barker, T., Turkey in Europe, New York, 1877.",
    "Bartusis, M. C., The Late Byzantine Army: Arms and Society, 1204–1453, 1992.",
    "Bodnar, E. W., the Isthmian Fortifications in oracular Prophecy, 1960.",
    "Bratianu, la question de l'aPProvisionnement de Constantinople Byzantion, 1929.",
    "Brehier, L., Vie et mort de Byzance, Paris, 1948.",
    "Browning, R., The Byzantine Empire, 1980.",
    "Burns, The Catalan Company and Europen Powers 1305-1311, 1954.",
    "Cantacuzenus, J., Historiarum, 1829 (and English Trans. by T. Miller, 1975).",
    "Carr, M., Friend or Foe? The Catalan Company as Proxy Actors, 2016.",
    "Castellan, G., History of the Balkans.",
    "Celik, S., Manuel II Palaeologus.",
    "Chalkokondyles, L., The Histories, trans. Anthony Kaldellis, 2014 (and 1996 ed. by N. Nicoloudis).",
    "Charanis, P., An Important short chronicle of Fourteenth century in Byzantion, 1938.",
    "Cheyney, E., The Dawn of A New Era.",
    "Chirol, The Turkis Empire 1288-1914, 1952.",
    "Choniates, N., O City of Byzantium: Annals of Niketas Choniates, trans. Harry J. Magoulias, 1984.",
    "Clavijo, Embassy To Tamerlane, 1403-1406, 1928.",
    "Creasy, E., History of the ottoman turks.",
    "Cydones, D., Correspondence, 1956-1960.",
    "Dennis, G., \"The Reign of Manuel II Paleologos in thessalonica\", 1960.",
    "Dereksen, D., the crescent and cross.",
    "Dersca, A., La Campagne de timur en Anatolie, 1977.",
    "Diehl, C., Etudes Byzantines, Introduction a L'Histoire de Byzance, Paris, 1905.",
    "Diehl, C., Figures Byzantines Deuxieme Serie, Paris, 1908.",
    "Dolger, F., Regesten der kaiserurkunden Des ostromichen Reiches.",
    "Doukas, Decline and Fall of Byzantium to the Ottoman Turks, trans. Harry J. Magoulias, 1975.",
    "Downey, G., \"The Tombs of the Byzantine Emperors...\", The Journal of Hellenic Studies, 1959.",
    "Failler, Chronologie et composition.",
    "Finlay, History of the Greece, 1877.",
    "Folda, J., Byzantine Art and Italian Panel Painting, 2015.",
    "Foss, C., Survey of medieval Castles of Anatlia II \"Nicomedia\", 1996.",
    "Gautier, P., un Recit Inedit Du siege De consantinole Par Les Turcs 1394-1402, 1965.",
    "Geanakoplos, D. J., Emperor Michael Palaeologus and the West, 1258–1282, 1959.",
    "Gibbons, H., The Foundation of the Ottoman Empire, 1916.",
    "Gill, J., Matrons and Brides of Fourteenth Century Byzantium, 1985.",
    "Gregoras, N., Byzantina Historia, ed. L. Schopen, 1829.",
    "Grousset, R., L'Empire Du Levant, Paris, 1946.",
    "Hammer, V., Histoire De L'Empire Ottoman, 1841-1853.",
    "Harris, J., Byzantium and the Crusades, 2nd ed., Bloomsbury Academic, 2014.",
    "Hearsy, J., City of Constantines 324-1453, 1966.",
    "Hidden, A., The ottoman Dynasty.",
    "Inalcik, H., The ottoman Empire.",
    "Jackson, G., Women Rulers throughout the Ages, 1999.",
    "Janin, La Thrace Byzantine, 1921.",
    "Jonquiere, Histoire de l'empire ottoman, Paris, 1914.",
    "Jorga, N., the Byzantine Empire, London, 1907.",
    "Joseph, G. I., Eugenius IV Popes of chirstian union, 1961.",
    "Kaldellis, A., Hellenism in Byzantium, Cambridge University Press, 2007.",
    "Kaldellis, A., The New Roman Empire: A History of Byzantium, Oxford University Press, 2023.",
    "Kazhdan, A. P. (ed.), The Oxford Dictionary of Byzantium (ODB), Oxford University Press, 1991.",
    "Kelly, J., Oxford Dictionary of Popes.",
    "Kulzer, A., Ostthrakien Europe, Tabula Imperii Byzantini, 2008.",
    "Laiou, A. E., Constantinople and the Latins: The Foreign Policy of Andronicus II, 1972.",
    "Lambros, Anonymous letter In verse To the Despot Constantine.",
    "Lavallee, T., Histoire De l'Empire ottoman, 1855.",
    "Le Beau, C., Histoire du Bas-Empire, Paris, 1885.",
    "Leunclauvus, Historiae Musulmanae Turcorum, 1591.",
    "Lodge, E., the End of the Middle Age, 1273-1453, 1928.",
    "Longnon, L'Empire latin de Constantinople et la principaute de moree, 1949.",
    "Maclyans, M., the City of Constantinople, 1968.",
    "Magdalino, P., The Empire of Manuel I Komnenos, 1143–1180, Cambridge University Press, 1993.",
    "Mavromatis, L., la Serbie de Milutin Byzance et l'occident, 1973-1974.",
    "Mazower, M., Salonica City of Ghosts, 1050-1453, 2005.",
    "Melvani, N., the tombs of the Palaiologan Emperors, 2018.",
    "Michaud, Histoire des Croisades, 1849.",
    "Miller, W., Essays of the latin orient, 1921.",
    "Millingen, A., Byzantine Constantinople.",
    "Mitsiou, E., \"The Monastery of Sosandra...\", Bulgaria Mediaevalis, 2011.",
    "Moncada, Espedicion de los Catalanes y Aragoneses contra Turcos y Griegos, 1840.",
    "Nicol, D. M., The Despotate of Epiros (1267-1479), Cambridge University Press, 1984.",
    "Nicol, D. M., The Immortal Emperor: the life and legend of Constantine Palaiologos, Cambridge, 1992.",
    "Nicol, D. M., The Last Centuries of Byzantium, 1261-1453, Cambridge University Press, 1993.",
    "Nicol, D. M., The Reluctant Emperor, A biography of John Cantacuzene, Cambridge, 1996.",
    "Ostrogorsky, G., Etienne Dusan et la Noblesse serbe dans la lutte contre Byzance, 1952.",
    "Ostrogorsky, G., History of the Byzantine State, trans. Joan Hussey, 1969.",
    "Pachymeres, G., De Michaele et Andronico Palaeologis libri, 1835.",
    "Philippides, M., Constantine XI Dragas Palaeologus (1404-1453): the last Emperor of Byzantium, 2019.",
    "Polemis, D. I., The Doukai: A Contribution to Byzantine Prosopography, The Athlone Press, London, 1968.",
    "Preas, E., The Destruction of the Greek Empire and The story of capture of Constantinople, 1968.",
    "Ramsay, W. M., The Historical Geography of Asia Minor, 1962.",
    "Rice, D. T., The Byzantines, New York, 1962.",
    "Richard, P., Mcbrien the pocket Guide to the Popes, 2006.",
    "Rosser, J., Historical Dictionary of Byzantium, 2001.",
    "Runciman, S., The last Byzantine Renaissance, Cambridge, 1970.",
    "Runciman, S., The Sicilian Vespers, Cambridge University Press, 1958.",
    "Schlumberger, G., Expedition des Almugavares ou Routiers Catalans en orient, 1924.",
    "Setton, Catalan Domination of Athens 1311-1388, 1975.",
    "Shaw, S., History of the ottoman Empire and mdern turkey, 1976.",
    "Slavi, Miscellanea Agostino Pertusi, 1981.",
    "Souttar, R., A short History of Mediaeval Peoples.",
    "Spandoune, Th., On the origin of the ottoman Emperors, 1997.",
    "Sphrantzes, G., Annales (and Chronicon minus, 1966).",
    "Sullivan, A., Byzantium in Eastern European visual Culture in the late Middle Ages, 2020.",
    "Syropoulos, les \"memoire\" du Grand Ecclesiarque de L'Eglise de Constantinople, 1971.",
    "Tafur, P., Travels and Adventures 1435–1439, London, 1926.",
    "Treadgold, W., A History of the Byzantine State and Society, Stanford University Press, 1997.",
    "Vannier, J.-F., The First Palaiologoi: A Genealogical and Prosopographical Study, Publications de la Sorbonne, Paris, 1986.",
    "Vasiliev, A. A., History of the Byzantine Empire, 324-1453, 1952 (and French trans: Histoire De L'Empire Byzantin 1081-1453, 1932).",
    "Verpeaux, J., Notes chronologiques sur les livres II et III du De Andronico Palaeologo, 1959.",
    "Voordechers, A Propos de la Renonciation Au trone de Andronic II, 1968.",
    "Weller, A., \"Marrying the Mongol Khans...\", Scandinavian Journal of Byzantine and Modern Greek Studies, 2016.",
    "Wilskman, J., The Campaign and Battle of Pelagonia 1259, Byzantinos Domos, 2009-2010.",
    "Wittek, Yazijioghlu Ali on the christian of the Dobrugen, 1952.",
    "Wolff, R. L., The Latin Empire of Constantinople, 1204-1261, 1969.",
    "Zachariadou, A., John VII (Alias Andronicus) Paleologus, 1977.",
    "Zakythinos, A., le Despotat grec de moree, Paris, 1932."
  ]
};
